# Generated by Django 5.2.6 on 2025-09-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alcohol_consumption',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Occasional', 'Occasional'), ('Regular', 'Regular')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primary_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Former', 'Former'), ('Current', 'Current')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
